name: Track Market Prices

on:
  schedule:
    # Morning batch (9 AM Central) - High priority items
    - cron: '0 14 * * *'  # 2 PM UTC = 9 AM Central
    # Afternoon batch (2 PM Central) - Medium priority items  
    - cron: '0 19 * * *'  # 7 PM UTC = 2 PM Central
    # Evening batch (7 PM Central) - Low priority items
    - cron: '0 0 * * *'   # 12 AM UTC = 7 PM Central (previous day)
    # Night batch (12 AM Central) - Full scan
    - cron: '0 5 * * *'   # 5 AM UTC = 12 AM Central
  workflow_dispatch:

jobs:
  track-market-prices:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: cd scripts && npm install
      - name: Run market price tracker
        env:
          TORN_API_KEY: ${{ secrets.TORN_API_KEY }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: cd scripts && node market-price-tracker.js 